# Generated by Django 5.0.6 on 2024-05-26 09:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idx', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100)),
                ('instructions', models.TextField()),
                ('cook_time_minutes', models.IntegerField()),
                ('servings', models.IntegerField()),
                ('difficulty', models.CharField(max_length=10)),
                ('cuisine', models.CharField(max_length=20)),
                ('calories_per_serving', models.IntegerField()),
                ('image', models.URLField()),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('ingredients', models.JSONField()),
                ('tags', models.JSONField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
